// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RecoverFlow.Infrastructure.Persistence;

#nullable disable

namespace RecoverFlow.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260713181042_AddAccountBacktest")]
    partial class AddAccountBacktest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecoverFlow.Domain.Entities.AccountBacktest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BreakdownJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("breakdown_json");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<long>("EstimatedFeeHighCents")
                        .HasColumnType("bigint")
                        .HasColumnName("estimated_fee_high_cents");

                    b.Property<long>("EstimatedFeeLowCents")
                        .HasColumnType("bigint")
                        .HasColumnName("estimated_fee_low_cents");

                    b.Property<long>("FailedAmountCents")
                        .HasColumnType("bigint")
                        .HasColumnName("failed_amount_cents");

                    b.Property<int>("FailedInvoiceCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_invoice_count");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("failure_reason");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<long>("RecoverableHighCents")
                        .HasColumnType("bigint")
                        .HasColumnName("recoverable_high_cents");

                    b.Property<long>("RecoverableLowCents")
                        .HasColumnType("bigint")
                        .HasColumnName("recoverable_low_cents");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("WindowDays")
                        .HasColumnType("integer")
                        .HasColumnName("window_days");

                    b.HasKey("Id")
                        .HasName("pk_account_backtests");

                    b.HasIndex("MerchantId")
                        .HasDatabaseName("ix_account_backtests_merchant_id");

                    b.ToTable("account_backtests", (string)null);
                });

            modelBuilder.Entity("RecoverFlow.Domain.Entities.CardUpdateSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FailedPaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("failed_payment_id");

                    b.Property<string>("NewPaymentMethodId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("new_payment_method_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_card_update_sessions");

                    b.HasIndex("FailedPaymentId")
                        .HasDatabaseName("ix_card_update_sessions_failed_payment_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_card_update_sessions_token");

                    b.ToTable("card_update_sessions", (string)null);
                });

            modelBuilder.Entity("RecoverFlow.Domain.Entities.EmailSequenceEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ClickedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("clicked_at");

                    b.Property<string>("EmailType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email_type");

                    b.Property<Guid>("FailedPaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("failed_payment_id");

                    b.Property<DateTime?>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<bool>("ResultedInRecovery")
                        .HasColumnType("boolean")
                        .HasColumnName("resulted_in_recovery");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<int>("SequenceStep")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_step");

                    b.HasKey("Id")
                        .HasName("pk_email_sequences");

                    b.HasIndex("FailedPaymentId")
                        .HasDatabaseName("ix_email_sequences_failed_payment_id");

                    b.ToTable("email_sequences", (string)null);
                });

            modelBuilder.Entity("RecoverFlow.Domain.Entities.FailedPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountCents")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_cents");

                    b.Property<DateTime?>("BilledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("billed_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("customer_email");

                    b.Property<string>("DeclineCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("decline_code");

                    b.Property<string>("DeclineReason")
                        .HasColumnType("text")
                        .HasColumnName("decline_reason");

                    b.Property<string>("FailureType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("failure_type");

                    b.Property<Guid?>("FeeInvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("fee_invoice_id");

                    b.Property<DateTime>("FirstFailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_failed_at");

                    b.Property<DateTime?>("LostAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lost_at");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<DateTime?>("RecoveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recovered_at");

                    b.Property<string>("RecoveryMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("recovery_method");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stripe_customer_id");

                    b.Property<string>("StripeInvoiceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stripe_invoice_id");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stripe_subscription_id");

                    b.HasKey("Id")
                        .HasName("pk_failed_payments");

                    b.HasIndex("FeeInvoiceId")
                        .HasDatabaseName("ix_failed_payments_fee_invoice_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_failed_payments_status");

                    b.HasIndex("MerchantId", "StripeInvoiceId")
                        .IsUnique()
                        .HasDatabaseName("ix_failed_payments_merchant_id_stripe_invoice_id");

                    b.ToTable("failed_payments", (string)null);
                });

            modelBuilder.Entity("RecoverFlow.Domain.Entities.FeeInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("BillableRecoveredCents")
                        .HasColumnType("bigint")
                        .HasColumnName("billable_recovered_cents");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("failure_reason");

                    b.Property<long>("FeeCents")
                        .HasColumnType("bigint")
                        .HasColumnName("fee_cents");

                    b.Property<long>("FloorTopUpCents")
                        .HasColumnType("bigint")
                        .HasColumnName("floor_top_up_cents");

                    b.Property<string>("HostedInvoiceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("hosted_invoice_url");

                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<string>("PeriodLabel")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("period_label");

                    b.Property<int>("RecoveredCaseCount")
                        .HasColumnType("integer")
                        .HasColumnName("recovered_case_count");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StripeInvoiceId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stripe_invoice_id");

                    b.Property<long>("TotalCents")
                        .HasColumnType("bigint")
                        .HasColumnName("total_cents");

                    b.HasKey("Id")
                        .HasName("pk_fee_invoices");

                    b.HasIndex("MerchantId")
                        .HasDatabaseName("ix_fee_invoices_merchant_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_fee_invoices_status");

                    b.ToTable("fee_invoices", (string)null);
                });

            modelBuilder.Entity("RecoverFlow.Domain.Entities.Merchant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("EncryptedStripeAccessToken")
                        .HasColumnType("text")
                        .HasColumnName("encrypted_stripe_access_token");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("plan");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings_json");

                    b.Property<string>("StripeAccountId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stripe_account_id");

                    b.Property<string>("StripePlatformCustomerId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stripe_platform_customer_id");

                    b.HasKey("Id")
                        .HasName("pk_merchants");

                    b.HasIndex("StripeAccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_merchants_stripe_account_id");

                    b.ToTable("merchants", (string)null);
                });

            modelBuilder.Entity("RecoverFlow.Domain.Entities.ProcessedWebhookEvent", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("EventId")
                        .HasName("pk_processed_webhook_events");

                    b.ToTable("processed_webhook_events", (string)null);
                });

            modelBuilder.Entity("RecoverFlow.Domain.Entities.RetryAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<DateTime?>("AttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempted_at");

                    b.Property<string>("DeclineCodeReceived")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("decline_code_received");

                    b.Property<Guid>("FailedPaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("failed_payment_id");

                    b.Property<string>("Result")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("result");

                    b.Property<DateTime>("ScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for");

                    b.HasKey("Id")
                        .HasName("pk_retry_attempts");

                    b.HasIndex("FailedPaymentId")
                        .HasDatabaseName("ix_retry_attempts_failed_payment_id");

                    b.HasIndex("ScheduledFor")
                        .HasDatabaseName("ix_retry_attempts_scheduled_for");

                    b.ToTable("retry_attempts", (string)null);
                });

            modelBuilder.Entity("RecoverFlow.Domain.Entities.AccountBacktest", b =>
                {
                    b.HasOne("RecoverFlow.Domain.Entities.Merchant", "Merchant")
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_backtests_merchants_merchant_id");

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("RecoverFlow.Domain.Entities.CardUpdateSession", b =>
                {
                    b.HasOne("RecoverFlow.Domain.Entities.FailedPayment", "FailedPayment")
                        .WithMany()
                        .HasForeignKey("FailedPaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_card_update_sessions_failed_payments_failed_payment_id");

                    b.Navigation("FailedPayment");
                });

            modelBuilder.Entity("RecoverFlow.Domain.Entities.EmailSequenceEntry", b =>
                {
                    b.HasOne("RecoverFlow.Domain.Entities.FailedPayment", "FailedPayment")
                        .WithMany("EmailEntries")
                        .HasForeignKey("FailedPaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_sequences_failed_payments_failed_payment_id");

                    b.Navigation("FailedPayment");
                });

            modelBuilder.Entity("RecoverFlow.Domain.Entities.FailedPayment", b =>
                {
                    b.HasOne("RecoverFlow.Domain.Entities.FeeInvoice", null)
                        .WithMany()
                        .HasForeignKey("FeeInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_failed_payments_fee_invoices_fee_invoice_id");

                    b.HasOne("RecoverFlow.Domain.Entities.Merchant", "Merchant")
                        .WithMany("FailedPayments")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_failed_payments_merchants_merchant_id");

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("RecoverFlow.Domain.Entities.FeeInvoice", b =>
                {
                    b.HasOne("RecoverFlow.Domain.Entities.Merchant", "Merchant")
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fee_invoices_merchants_merchant_id");

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("RecoverFlow.Domain.Entities.RetryAttempt", b =>
                {
                    b.HasOne("RecoverFlow.Domain.Entities.FailedPayment", "FailedPayment")
                        .WithMany("RetryAttempts")
                        .HasForeignKey("FailedPaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_retry_attempts_failed_payments_failed_payment_id");

                    b.Navigation("FailedPayment");
                });

            modelBuilder.Entity("RecoverFlow.Domain.Entities.FailedPayment", b =>
                {
                    b.Navigation("EmailEntries");

                    b.Navigation("RetryAttempts");
                });

            modelBuilder.Entity("RecoverFlow.Domain.Entities.Merchant", b =>
                {
                    b.Navigation("FailedPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
